name: Koyeb Deployment

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  deploy:
    name: Deploy to Koyeb
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Koyeb CLI
        uses: koyebhq/action-setup-koyeb@v1
        with:
          koyeb-api-key: ${{ secrets.KOYEB_API_KEY }}
          koyeb-account-id: ${{ secrets.KOYEB_ACCOUNT_ID }}

      - name: Build and Deploy
        run: |
          # Build your application here, e.g., using Maven, Gradle, or npm
          # Deploy your application using the Koyeb CLI
          # Example: koyeb deploy my-service --image my-image:latest
